version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: liive
      POSTGRES_PASSWORD: liive
      POSTGRES_DB: liivedb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_DATA_VOLUME:-postgres_data}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liive -d liivedb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrator:
    build:
      context: ./backend
      args:
        APP_NAME: liive-migrator
    environment:
      DATABASE_URL: postgresql://liive:liive@postgres:5432/liivedb
      POSTGRES_DB: liivedb
    depends_on:
      postgres:
        condition: service_healthy

  auth-api:
    build:
      context: ./backend
      args:
        APP_NAME: liive-auth-api
    environment:
      DATABASE_URL: postgresql://liive:liive@postgres:5432/liivedb
      POSTGRES_DB: liivedb
      PORT: 8000
      HOST: 0.0.0.0
      UVICORN_EXTRA_ARGS: "--reload --workers 1"
    ports:
      - "8000:8000"
    depends_on:
      migrator:
        condition: service_completed_successfully

  ws-api:
    build:
      context: ./backend
      args:
        APP_NAME: liive-ws-api
    environment:
      DATABASE_URL: postgresql://liive:liive@postgres:5432/liivedb
      POSTGRES_DB: liivedb
      PORT: 8003
      HOST: 0.0.0.0
      UVICORN_EXTRA_ARGS: "--reload --workers 1"
    ports:
      - "8003:8003"
    depends_on:
      migrator:
        condition: service_completed_successfully

  chat-api:
    build:
      context: ./backend
      args:
        APP_NAME: liive-chat-api
    environment:
      DATABASE_URL: postgresql://liive:liive@postgres:5432/liivedb
      POSTGRES_DB: liivedb
      PORT: 8001
      HOST: 0.0.0.0
      UVICORN_EXTRA_ARGS: "--reload --workers 1"
    ports:
      - "8001:8001"
    depends_on:
      migrator:
        condition: service_completed_successfully

volumes:
  postgres_data:
  postgres_data_test:
