version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: liive
      POSTGRES_PASSWORD: liive
      POSTGRES_DB: liivedb
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_DATA_VOLUME:-postgres_data}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liive -d liivedb"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  migrator:
    build:
      context: ./backend
      dockerfile: liive-migrator/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_USER=liive
      - DB_PASSWORD=liive
      - DB_NAME=liivedb

  ws-api:
    build:
      context: ./backend
      dockerfile: liive-ws-api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      migrator:
        condition: service_completed_successfully
      redis:
        condition: service_started
    environment:
      - DB_HOST=postgres
      - DB_USER=liive
      - DB_PASSWORD=liive
      - DB_NAME=liivedb
      - REDIS_HOST=redis

  rest-api:
    build:
      context: ./backend
      dockerfile: liive-rest-api/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      migrator:
        condition: service_completed_successfully
      redis:
        condition: service_started
    environment:
      - DB_HOST=postgres
      - DB_USER=liive
      - DB_PASSWORD=liive
      - DB_NAME=liivedb
      - REDIS_HOST=redis

  message-storer:
    build:
      context: ./backend
      dockerfile: liive-message-storer/Dockerfile
    depends_on:
      migrator:
        condition: service_completed_successfully
      redis:
        condition: service_started
    environment:
      - DB_HOST=postgres
      - DB_USER=liive
      - DB_PASSWORD=liive
      - DB_NAME=liivedb
      - REDIS_HOST=redis

  auth:
    build:
      context: ./backend
      dockerfile: liive-auth/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      migrator:
        condition: service_completed_successfully
      redis:
        condition: service_started
    environment:
      - DB_HOST=postgres
      - DB_USER=liive
      - DB_PASSWORD=liive
      - DB_NAME=liivedb
      - REDIS_HOST=redis

  user-manager:
    build:
      context: ./backend
      dockerfile: liive-user-manager/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      migrator:
        condition: service_completed_successfully
      redis:
        condition: service_started
    environment:
      - DB_HOST=postgres
      - DB_USER=liive
      - DB_PASSWORD=liive
      - DB_NAME=liivedb
      - REDIS_HOST=redis

volumes:
  postgres_data:
  postgres_data_test: 